---
title: How to Make Awesome R Markdown for Blogdown
author: John Houghton
date: '2018-11-13'
slug: how-to-make-awesome-r-markdown-for-blogdown
categories:
  - Markdown
  - R
tags: []
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---
    
```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)
```

```{r cache=TRUE}
knitr::read_chunk('~/Documents/Github/r_snippets/blogdown.R')
```
# R Notebook Options
```{r knitr_optionss, include=TRUE}
```

# Great Article on configuration / tips & tricks
https://medium.com/@jeffmcmorris/tips-and-tricks-for-building-a-theme-in-hugo-4806bdd747d7

## blogdown documentation here: https://bookdown.org/yihui/rmarkdown/html-document.html
## Knitr Examples on Github
https://github.com/yihui/knitr-examples
## CheatSheet 
https://www.ethz.ch/content/dam/ethz/special-interest/math/statistics/sfs/Education/Advanced%20Studies%20in%20Applied%20Statistics/course-material-1719/Datenanalyse/rmarkdown-2.pdf

# Markdown Themes
### rmdformats package  https://github.com/juba/rmdformats
The github README.md provides some good examples

## Here's a great collection of examples of themes
http://www.datadreaming.org/post/r-markdown-theme-gallery/

## Custom Build Functions
https://yutani.rbind.io/post/2017-10-25-blogdown-custom/

